<footer class="page-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <h5 class="text-uppercase">Crédits</h5>
                <p>
                    Projet réalisé par Duterte Sébastien et Melvin Beaussart<br>
                    Nous esperons que notre version du jeu Siam vous plaira.
                </p>
            </div>
            <div class="col-md-6">
                <h5 class="text-uppercase">Règles</h5>
                <p>Mettre quelques petites règles ici</p>
            </div>
        </div>
    </div>
</footer>